### ISSUE TITLE
Enemy AI

### ISSUE THREAD

**Issue by nnickodem** [nnickodem/NetworkDomination#30]
As a player, I want the enemy to on some level react to my actions so that it feels as though I'm playing against something that isn't static

**Comment by nnickodem** [comment]
Blocked by #70 

could use something like shortest path to non-friendly to determine next target

**Comment by T0YMAK3R** [comment]
If we build spanning trees for each device, it would be trivial to find the closest device based on weight.  Then it would be a matter of stepping through the closest devices, by weighted path, and checking if they belong to the player (or even neutral, in case of enemy hackers), if they do: attack.

**Comment by T0YMAK3R** [comment]
For a more advanced AI, we could also prioritize device type.  Firewalls, then routers, then switches, then end-devices.  This would enable the AI to work for real map control.

**Comment by nnickodem** [comment]
Blocked by #48
